import type { Option } from '@/lib/types';
import type { SearchFilters } from '@/lib/domain';
export function Search({ q = '', where = '' }: {
    q?: string;
    where?: string;
}) { return <form className="search" action="/jobs"><label>Что ищешь?<input type="search" name="q" defaultValue={q} placeholder="Например: грузчик, курьер, водитель" maxLength={200}/></label><label>Где?<input name="where" defaultValue={where} placeholder="Например: Новосибирск, метро Площадь Ленина" maxLength={200}/></label><p className="search-hint">Подсказка: можно указать профессию, город, улицу или метро.</p><button className="primary">Найти подработку</button></form>; }
export function Filters({ f, categories }: {
    f: SearchFilters;
    categories: Option[];
}) { return <form action="/jobs" className="filters"><h2>Уточнить поиск</h2><input type="hidden" name="q" value={f.q}/><input type="hidden" name="where" value={f.where}/><div className="filter-fields"><label>Категория<select name="category" defaultValue={f.category}><option value="">Все категории</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Оплата от, ₽ / смена<input type="number" name="min" min="0" defaultValue={f.min ?? ''} placeholder="Например, 3000"/></label><label>Когда<select name="day" defaultValue={f.day || ''}><option value="">Любая дата</option><option value="today">Сегодня</option><option value="tomorrow">Завтра</option>{f.day && <option value={f.day}>{f.day}</option>}</select></label></div><label className="check"><input type="checkbox" name="instant" value="1" defaultChecked={f.instant}/>С оплатой сразу</label><label className="check"><input type="checkbox" name="employer" value="1" defaultChecked={f.employer}/>От работодателя</label><label className="check"><input type="checkbox" name="address" value="1" defaultChecked={f.address}/>С адресом</label><button className="primary">Применить</button><p><a href="/jobs" className="small muted">Сбросить фильтры</a></p><p className="small muted">Минимальная оплата сравнивается за смену, не за месяц или час.</p></form>; }
