export type Job = {
    id: string;
    title: string;
    description: string;
    city: string;
    city_id: string;
    category: string | null;
    address_raw: string | null;
    address_normalized: string | null;
    salary_min: number | null;
    salary_max: number | null;
    salary_type: string | null;
    payment_type: string | null;
    employment_type: string | null;
    date_start: string | null;
    date_end: string | null;
    time_start: string | null;
    time_end: string | null;
    contact_phone: string | null;
    contact_telegram: string | null;
    contact_email: string | null;
    source_type: string;
    source_url: string | null;
    original_text: string | null;
    employer_id: string | null;
    status: string;
    published_at: string | null;
    expires_at: string | null;
    created_at: string;
    photo_url: string | null;
    commercial?: number;
    ai_confidence: number | null;
    moderation_reason: string | null;
};
export type Option = {
    id: string;
    name: string;
    slug?: string;
};
