import { requireAdmin } from '@/lib/auth';
import { check } from '@/lib/service-db';
import { ActionForm } from '@/components/action-form';
import { saveSource, importMessage } from '@/app/actions';
export default async function Telegram() {
    const { client } = await requireAdmin();
    const { data: sources } = check(await client.from('telegram_sources').select('*').order('created_at').limit(100));
    const { data: cities } = check(await client.from('cities').select('id,name').eq('active', true));
    const { data: messages } = check(await client.from('telegram_messages').select('*').order('created_at', { ascending: false }).limit(20));
    const { data: runs } = check(await client.from('parser_runs').select('*').order('created_at', { ascending: false }).limit(20));
    function form(s?: Record<string, string | boolean>) { return <ActionForm action={saveSource}><input type="hidden" name="id" value={String(s?.id || '')}/><label>Название<input name="name" required defaultValue={String(s?.name || '')} placeholder="Работа Новосибирск"/></label><label>Username канала<input name="username" required defaultValue={String(s?.username || '')} placeholder="rabota154NsK"/><small>Без @ и https://t.me/.</small></label><label>Город<select name="city_id" defaultValue={String(s?.city_id || '')}>{cities?.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Способ импорта<select name="adapter" defaultValue={String(s?.adapter || 'manual')}><option value="manual">Ручной импорт</option><option value="bot">Bot API, только доступные боту каналы</option></select></label><label>Telegram chat_id<input name="chat_id" defaultValue={String(s?.chat_id || '')} placeholder="-100…"/><small>Нужен только для Bot API. Не угадывайте, возьмите из Telegram update.</small></label><label className="check"><input name="active" type="checkbox" defaultChecked={Boolean(s?.active)}/>Источник активен</label></ActionForm>; }
    return <><h1>Источники Telegram</h1><p className="message">Для чужого канала используйте ручной импорт с правом на публикацию текста. Бот не читает произвольные каналы и старую историю.</p>{sources?.map(s => <details key={s.id}><summary>{s.name} · @{s.username} · {s.active ? 'активен' : 'отключён'}</summary>{form(s)}{s.last_error && <p role="alert">{s.last_error}</p>}</details>)}<details><summary>+ Добавить источник</summary>{form()}</details><hr className="divider"/><h2>Импортировать сообщение</h2><ActionForm action={importMessage} label="Сохранить оригинал и отправить в очередь"><label>Источник<select name="source_id" required>{sources?.filter(s => s.active).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Номер сообщения<input name="telegram_message_id" type="number" min={1} required placeholder="12345"/><small>Последнее число в ссылке t.me/канал/12345.</small></label><label>Дата оригинала, ISO 8601<input name="message_date" required placeholder="2026-09-07T08:00:00Z"/><small>Укажите фактическую дату сообщения с часовым поясом, не сегодняшнюю по умолчанию.</small></label><label>Полный оригинальный текст<textarea name="message_text" required maxLength={20000} placeholder="Вставьте текст целиком, не заменяя неизвестные данные выдуманными"/></label></ActionForm><h2 style={{ marginTop: 32 }}>Последние 20 сообщений</h2>{messages?.map(m => <details key={m.id}><summary>Сообщение {m.telegram_message_id} · {new Date(m.message_date).toLocaleString('ru-RU')}</summary><p style={{ whiteSpace: 'pre-wrap' }}>{m.message_text}</p><a href={m.message_url} target="_blank" rel="noopener noreferrer">Оригинал ↗</a></details>)}<h2 style={{ marginTop: 32 }}>Последние обработки</h2>{runs?.map(r => <div className="data-row" key={r.id}>{r.provider} · {r.error || 'Обработано'}<p className="small muted">{r.created_at}</p></div>)}</>;
}
